"""add cognito_sub to users

Revision ID: 6ecb882704e8
Revises: a001ecbdfd3e
Create Date: 2026-02-28 10:22:56.069896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ecb882704e8'
down_revision: Union[str, Sequence[str], None] = 'a001ecbdfd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    incident_status = postgresql.ENUM(
    "OPEN",
    "IN_PROGRESS",
    "RESOLVED",
    "CLOSED",
    name="incident_status",
    )
    incident_status.create(op.get_bind(), checkfirst=True)  
    op.execute("UPDATE incidents SET status = 'OPEN' WHERE status IS NULL")
    op.execute("UPDATE incidents SET status = UPPER(status)")
    op.execute("UPDATE incidents SET status = 'IN_PROGRESS' WHERE status IN ('INPROGRESS','IN-PROGRESS','IN PROGRESS')")
    op.execute(
       "ALTER TABLE incidents "
       "ALTER COLUMN status TYPE incident_status "
       "USING status::incident_status"
    )
    op.alter_column('incidents', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.add_column('users', sa.Column('cognito_sub', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_cognito_sub'), 'users', ['cognito_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cognito_sub'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'cognito_sub')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('incidents', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='incident_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('incidents', 'updated_at')
    op.drop_table('incident_events')
    # ### end Alembic commands ###
